baseURL: "https://clemspace.github.io/"
title: Clément Castellon Personal Page
paginate: 5
#theme: PaperMod
#theme: ["PaperMod"]
theme: "PaperMod"
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


minify:
  disableXML: true
  #minifyOutput: false

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Clemspaces' space
  description: "Personal Lair Clemspace"
  keywords: [Blog, Portfolio, PaperMod]
  author: Clément Castellon
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2, January 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: /favicon.ico
    favicon16x16: /favicon-16x16.png
    favicon32x32: /favicon-32x32.png
    apple_touch_icon: /apple-touch-icon.png
    safari_pinned_tab: /apple-touch-icon.png

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 25

  # home-info mode
  homeInfoParams:
    enabled: true
    Title: "Hi there \U0001F44B"
    Content: "Welcome to my secret lil'space 🪐"

  socialIcons:
    - name: x
      url: "https://x.com/Clemspace"
    - name: Malt
      url: "https://www.malt.fr/profile/clementcastellon"
    - name: github
      url: "https://github.com/Clemspace"

  googleAnalytics: G-990NN2DZ4S

  analytics:
    google:
      SiteVerificationTag: G-990NN2DZ4S
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/Clemspace/Clemspace.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: github
      name: github.com
      url: https://github.com/Clemspace
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai